# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: mRNA_vertebrate_mammalian_NM_vertebrate_mammalian_mRNA_separators
  - /optimizer: adamw
  - /scheduler: cosine_warmup_timm
  - /callbacks: [base, checkpoint]

train:
  monitor: test/loss
  mode: min

wandb:
  project: mRNA_vertebrate_mammalian_NM_vertebrate_mammalian_mRNA_separators

task:
  _name_: lm
  loss: cross_entropy
  torchmetrics: ['perplexity', 'num_tokens']

encoder: null
decoder: null
