_name_: mRNA
fasta_file: data/mRNA_data/complete_XM_mRNA_filtered_separators.fasta
# fasta_file: "/raid_elmo/home/lr/zym/data/protein_data/Pfam-A-new.fasta"
# prot14m_dir: "/raid_elmo/home/lr/zym/data/protein"
dataset_name: mRNA
tokenizer_name: char
cache_dir: null
max_length: 1024
add_eos: True
batch_size: 8 # per GPU
batch_size_eval: ${eval:${.batch_size} * 1}
num_workers: 4 # For preprocessing only
shuffle: True
pin_memory: True
__train_len: ${div_up:1_000_000_000, ${.max_length}}
__l_max: ${.max_length}
